### ISSUE TITLE
预训练模型下载链接

### ISSUE THREAD

**Issue by Tekapo-s** [PengtaoJiang/L2G#16]
预训练模型ilsvrc-cls_rna-a1_cls1000_ep-0001.params下载链接打不开，https://drive.google.com/file/d/15F13LEL5aO45JU-j45PYjzv5KW5bn_Pn/view

**Comment by SakaRenko** [comment]
你好，你可以尝试用[这个链接](https://pan.baidu.com/s/1lmsdh_B_3mp001RNYtbPGg )下载预训练模型，其中提取码为1b3s。
