### ISSUE TITLE
box_generation 的作用

### ISSUE THREAD

**Issue by Tekapo-s** [PengtaoJiang/L2G#18]
您好，在阅读您的代码后，在您LoadData.py中的 box_generation 函数有些难理解，可以向您请教一下box_generation 中生成boxes的过程，以及最后生成的boxes的含义和用途吗？十分感谢！

**Comment by SakaRenko** [comment]
您好，代码中的box_generation可以分为两个步骤，第一个步骤是在原图像的四角各选取一个box，第二个步骤是在原图像中随机选取区域作为boxes，box的总数量为参数中给定的数量，boxes的大小均为local view图像的大小。生成这些box后，模型会根据这些生成的box在图像中切割图像作为论文中提到的local view参与训练。
希望能够解决你的疑惑。
