### ISSUE TITLE
about reproducing

### ISSUE THREAD

**Issue by qjadud1994** [PengtaoJiang/L2G#20]
Hello.
Thank you for sharing the impressive work, L2G!

I tried to reproduce the L2G following the implementation script, however, I obtained about 66% mIoU on VOC2012, which is far behind the 72.1% of paper mIoU.

I used the bellow scripts.

1. use the [Pretrained models for VOC](https://drive.google.com/file/d/1Yc-LZ4bTM_1arpPBId6CMP9I2gOrDkdi/view?usp=sharing), without `./train_l2g_sal_voc.sh `
2. run `./test_l2g_voc.sh`
3. run `./gen_gt_voc.sh`
4. run deeplab v2 `python main.py train --config-path configs/voc12_resnet_dplv2.yaml`

Could you check reproducing of this work?
Are there any recommendations about this result?

~~~
# data/scores/voc12_resnet_v2/deeplabv2_resnet101_msc/val/scores_crf.json
{
    "Class IoU": {
        "0": 0.8893978389769717,
        "1": 0.7332514237124688,
        "2": 0.2647600116462558,
        "3": 0.7530019963539774,
        "4": 0.6229389456497264,
        "5": 0.6844399420943811,
        "6": 0.8477865759662723,
        "7": 0.7323184116750477,
        "8": 0.8361064618817893,
        "9": 0.268236496479961,
        "10": 0.7934048627881579,
        "11": 0.4293026338035794,
        "12": 0.7782026771867929,
        "13": 0.7793843619160901,
        "14": 0.6993258587392808,
        "15": 0.7108989092335944,
        "16": 0.5175071559996408,
        "17": 0.7581466783853126,
        "18": 0.4200272117472957,
        "19": 0.8026335398365552,
        "20": 0.5178384991250041
    },
    "Frequency Weighted IoU": 0.839895707892765,
    "Mean Accuracy": 0.8471590439388089,
    "Mean IoU": 0.6589957377713407,
    "Pixel Accuracy": 0.9036374933774816
}
~~~

**Comment by SakaRenko** [comment]
Hello, from your description, I guess there may be some mistakes in the evaluation code or the deeplab code. 
Can you give some more information about your reproducing? For example, I want to know the miou of the pseudo label, it should be around 70%.

**Comment by qjadud1994** [comment]
After running `python3 scripts/evaluate_mthr_voc.py` in `./test_l2g_voc.sh`, I obtained `runs/exp_voc/ms/result.txt`.

In the txt file, the best miou of the pseudo label is 
~~~
"Mean IoU": 0.6946978949643782,
"Mean_Precision": 0.801263451942538,
"Mean_Recall": 0.8297810616704436,
"Threshold": 0.25
~~~

**Comment by SakaRenko** [comment]
Those data is good, and I suppose the problem must be in the deeplab phase.
I hope you can provide the training log for the deeplab so that we can figure out where the problem is.
Thanks very much.

**Comment by qjadud1994** [comment]
The training logs, checkpoint, and result json files are [here](https://drive.google.com/file/d/1Qcxrzy4I_IXzfewM-9XcjMdjjVzYQZXl/view?usp=share_link).

![image](https://user-images.githubusercontent.com/20681582/213467086-700759b0-0b6e-4d5d-8fec-136b038eab96.png)

**Comment by SakaRenko** [comment]
Sorry for the late reply.
I run the test code with the checkpoint you provide, but the miou is around 70% before crf, which is much higher.
I guess you may changed some important settings related to the test phase, do you have any ideas about that?

**Comment by qjadud1994** [comment]
Sorry for bothering you.
I guess there is an error in my validation dataset :(

Thank you for your comprehensive cooperation.
