### ISSUE TITLE
The pretrain model link about the  classification network is dead

### ISSUE THREAD

**Issue by awei-97** [PengtaoJiang/L2G#22]
This link  **https://drive.google.com/file/d/15F13LEL5aO45JU-j45PYjzv5KW5bn_Pn/view** is not found.

**Comment by SakaRenko** [comment]
Sorry for the late reply.
You can download the classification model [here](https://pan.baidu.com/s/1vP8O0RPJKXM0HPhVCn7wXw) with access code t4ce.
We will change the URL in the readme later.
