### ISSUE TITLE
框架图注意力图如何生成的？

### ISSUE THREAD

**Issue by cny1234** [PengtaoJiang/L2G#23]
论文网络框架图的局部注意力图是在哪步生成的，跑完程序没见到呀？attention是全局的  ，cam_png也不是，是需要自己处理吗？

**Comment by SakaRenko** [comment]
局部注意力图是在训练时作为训练用的注意力图生成的，并没有特意保存下来。
如果你想对局部注意力图进行可视化的话，可能需要修改训练代码或者在测试时修改输入的图像。

**Comment by cny1234** [comment]
测试的时候使用局部图篇的话因为已经经过训练过程，所以会导致局部注意力图和最初的有所出入；训练时的局部注意力图是代码中的feat_local_label吗？我尝试好几次都很难保存下来

**Comment by SakaRenko** [comment]
确实是使用feat_local_label，请问你在保存时具体是遇到了怎样的困难呢？
