### ISSUE TITLE
注意力图和伪分割标签的生成之间是如何进行的？

### ISSUE THREAD

**Issue by cny1234** [PengtaoJiang/L2G#26]
您好，我看论文中似乎没有提到关于伪分割是如何通过注意力图生成的，代码里也没有使用显著图来生成伪标签，那注意力图是如何用于生成伪标签的呢？

**Comment by SakaRenko** [comment]
伪分割通过计算不同类注意力图在某个像素上的哪个类的响应值最大来决定。
除此之外，因为背景没有注意力图，因此我们把背景的注意力图设置为在不同像素上都相同的一个常数。
