### ISSUE TITLE
消融实验

### ISSUE THREAD

**Issue by cny1234** [PengtaoJiang/L2G#27]
实验1中使用滑动窗口，局部图像和L2G方法比较mIoU值的时候，用CAM作的基线，但原始CAM提出时没有经过分割；所以这个实验是把CAM生成注意力图的方法替换成了本文中的注意力生成方法吗

**Comment by SakaRenko** [comment]
本文生成注意力图的方法和cam中生成注意力图的方法是一样的，我们把cam的注意力生成方法在我们的实验框架下进行了复现。
