### ISSUE TITLE
你好，能否开源一下L2G在训练过程中的evaluate的代码

### ISSUE THREAD

**Issue by JimmyMa99** [PengtaoJiang/L2G#3]
我尝试去为L2G加入一些新的模块，但是在写训练过程中使用的evaluate的时候会出现爆显存的问题，然后我想向您寻求L2G在训练过程中的evaluate的代码

**Comment by Lin-7** [comment]
您好，请问一下，您使用本代码训练分类器的时候局部损失会出现nan吗？您的batchsize设置为多少呢？

**Comment by JimmyMa99** [comment]
> 您好，请问一下，您使用本代码训练分类器的时候局部损失会出现nan吗？您的batchsize设置为多少呢？

我使用bs=3，在3090*2的显卡下不会出现nan

**Comment by Lin-7** [comment]
这是来自QQ邮箱的自动回复邮件。已收到您的邮件~

**Comment by Lin-7** [comment]
好的，谢谢~
