### ISSUE TITLE
resnet模型

### ISSUE THREAD

**Issue by wchen002** [PengtaoJiang/L2G#32]
您好，能提供一下'ilsvrc-cls_rna-a1_cls1000_ep-0001.params'这个文件吗，谷歌云盘的地址失效了，非常感谢。

**Comment by PengtaoJiang** [comment]
https://pan.baidu.com/share/init?surl=vP8O0RPJKXM0HPhVCn7wXw  
密码 t4ce

**Comment by wchen002** [comment]
感谢！
