### ISSUE TITLE
怎么用自己的数据集？

### ISSUE THREAD

**Issue by Kiwi-xd** [PengtaoJiang/L2G#33]
您好，这个如果我想用自己的数据集训练生成伪标签，该怎么做？我看到这里似乎没有自己训练的代码。

**Comment by SakaRenko** [comment]
你好，我们只提供了在coco和voc上训练的代码，如果你想用自己的数据集的话，可以考虑参照utils/datasets.py对数据集处理的代码进行编写。
同时，如果你想要用显著图的话，可以直接使用预训练的PoolNet生成显著性图。
