### ISSUE TITLE
request for initial weights of classification

### ISSUE THREAD

**Issue by sepehrAmini** [PengtaoJiang/L2G#35]
Hi. regarding this paragraph:

'''Download the [pretrained model 提取码：t4ce](https://pan.baidu.com/share/init?surl=vP8O0RPJKXM0HPhVCn7wXw) to initialize the classification network and put it to ./models/.'''

Could you please upload the weights to google drive? I live outside of China and cannot create a Baidu account. 
It would be much kind and considerate of you. 

Thank you

**Comment by PengtaoJiang** [comment]
https://drive.google.com/file/d/1WvSkPfAtfPzyxcgG58a1RlRayMYb3FBc/view?pli=1
