### ISSUE TITLE
crop_size的问题

### ISSUE THREAD

**Issue by Jiax323** [PengtaoJiang/L2G#37]
您好，请问您的方法中crop_size大小是否会影响模型的精度，因为您局部图像的标签和全局图像标签是一致的，但是crop_size过小的话，局部图像可能会出现全是背景的情况，但是类别标签为1，这样是否会导致精度下降呢？

**Comment by PengtaoJiang** [comment]
实际上不会有影响，而且局部图像全是背景的情况可以看作为一种正则化。
