### ISSUE TITLE
bg_threshold问题

### ISSUE THREAD

**Issue by ChenWang0210** [PengtaoJiang/L2G#38]
您好，想问下bg_threshold的作用是什么

**Comment by SakaRenko** [comment]
你好
我想你说的bg threshold应该是train 12g sal voc,pyl(https://github.com/PengtaoJiang/L2G/blob/main/scripts/train 2g sal voc,py)中的bg thr? 这个参数的作用是筛选掉响应较低的类，不过在实验中发现这个参数设置为接近0甚至等于0的情况下效果最好，所以设置为0。
希望能对你有帮助

**Comment by ChenWang0210** [comment]
不好意思我没有说清楚，我说的是[evaluate_mthr_voc.py](https://github.com/PengtaoJiang/L2G/blob/main/scripts/evaluate_mthr_voc.py)中的’--thr‘参数，也就是[0.1, 0.15, 0.2, 0.25, 0.3]

**Comment by PengtaoJiang** [comment]
你好，这个参数是用来测不同背景阈值下伪标签的mIoU。

**Comment by SakaRenko** [comment]
这个参数是用来确定前景大小的。在弱监督语义分割中，通常会通过激活值的大小是否大于某个阈值确定这个像素是否属于前景，而这里的thr就是这个阈值。

**Comment by ChenWang0210** [comment]
明白了，非常感谢您的回复！
