### ISSUE TITLE
关于Attention maps的问题

### ISSUE THREAD

**Issue by ljt1540413344** [PengtaoJiang/L2G#4]
你好，我尝试在VOC2012数据集上测试你们的代码时发现，生成pseudo label的阶段中缺少了attention maps，然而我并没有找到你们提供了工具加载checkpoint生成这份东西的代码，所以我想请教一下，你们是在代码的哪个阶段生成这个attention maps的？

**Comment by SakaRenko** [comment]
你好，attention maps是在代码/scripts/test_l2g_voc.py中生成的（如果你是在VOC2012数据集上测试的话）。代码还提供了test_l2g_voc.sh从而生成attention maps并测试其质量。
希望能够有所帮助。

**Comment by linjiatai** [comment]
> 你好，attention maps是在代码/scripts/test_l2g_voc.py中生成的（如果你是在VOC2012数据集上测试的话）。代码还提供了test_l2g_voc.sh从而生成attention maps并测试其质量。 希望能够有所帮助。

好的感谢你的回答，我也发现是我脚本的运行顺序颠倒了，现在问题已经解决～

**Comment by ljt1540413344** [comment]
> 你好，attention maps是在代码/scripts/test_l2g_voc.py中生成的（如果你是在VOC2012数据集上测试的话）。代码还提供了test_l2g_voc.sh从而生成attention maps并测试其质量。 希望能够有所帮助。

感谢你的回答，我也发现是我运行脚本的顺序颠倒了，现在问题已经解决～
