### ISSUE TITLE
关于epoch

### ISSUE THREAD

**Issue by ChenWang0210** [PengtaoJiang/L2G#40]
您好，我用您的实验设置进行了训练，但在第4到5个epoch时模型就已经收敛了，请问为什么要设置10个epoch呢？谢谢！

**Comment by PengtaoJiang** [comment]
感谢你的关注。我们没有对训练epoch做过消融实验。 不过5 epoch的性能和10 epoch 性能差异不大。

**Comment by ChenWang0210** [comment]
明白了，感谢您的回复！
