### ISSUE TITLE
densecrf

### ISSUE THREAD

**Issue by xiangweikang** [PengtaoJiang/L2G#45]
Hello, currently, most papers perform post-processing with denseCRF when comparing performance. I would like to ask how to implement denseCRF optimization for the localization maps and segmentation results in our project's code?

**Comment by PengtaoJiang** [comment]
Hi, @xiangweikang, thanks for your interest. 
For crf using in segmentation results, the code is originally equip with the crf post-processing.  Please refer to the readme in deeplab-pytorch folder, "https://github.com/PengtaoJiang/L2G/tree/main/deeplab-pytorch" .  For refining localization maps, please refer to the code in "https://github.com/jiwoon-ahn/psa/blob/9493e59bef16687ecb4821387e38e6460857f508/infer_cls.py#L90C4-L90C4"
