### ISSUE TITLE
pascal voc测试结果问题

### ISSUE THREAD

**Issue by pur-suit** [PengtaoJiang/L2G#47]
您好，我按照readme产生了pseudo_seg_labels，miou是70.3，将伪掩码拿去deeplabv2_resnet监督训练（这里我将train_aug.txt中的所有SegmentationClassAug目录换成了所有pseudo_seg_labels目录），训练之后测试阶段加载得到的checkpoint_final.pth，但是在val上的结果非常差，miou只有22%左右，不过我的预训练权重是按照deeplab的readme转换得到的：Generate deeplabv2_resnet101_msc-vocaug.pth from train2_iter_20000.caffemodel ，是这个vocaug.pth，不知道是否是这个造成了影响呢？

**Comment by PengtaoJiang** [comment]
@pur-suit 您好，初始化模型可以使用我们给的模型，以确保模型能初始化成功。

**Comment by pur-suit** [comment]
好的，谢谢解答！
