### ISSUE TITLE
流程存在问题，按readme第二阶段分割流程没有使用伪标签

### ISSUE THREAD

**Issue by JimmyMa99** [PengtaoJiang/L2G#49]
流程中生成的伪标签为 `./data/voc12/pseudo_seg_labels/`，但用Deeplab训练分割的时候是使用的PascalVOC12 的 SegmentationClass，请问是代码版本未修改吗？

**Comment by YuqiYang213** [comment]
你好，从`deeplab-pytorch/data/datasets/voc12/train_aug.txt`这个列表文件中可以看出来，第二阶段分割流程会读取`./data/voc12/pseudo_seg_labels/`里生成的伪标签而非SegmentationClass，希望能够帮到你。

**Comment by JimmyMa99** [comment]
了解，感谢回复
