### ISSUE TITLE
下载数据集的问题

### ISSUE THREAD

**Issue by ljt1540413344** [PengtaoJiang/L2G#5]
你好，你们提供的PASCAL VOC下载地址[PASCAL VOC 2012](https://drive.google.com/file/d/1jnHE6Sau0tHI7X6JQKhzHov-vseYbrf9/view?usp=sharing)貌似下载下来大小是0k，不知道是不是你们上传出错了，希望能得到你们的帮助～

**Comment by SakaRenko** [comment]
你好，主页上的下载链接因为操作问题现在无法下载了，我们也会想办法解决这个问题。
如果你现在还需要PASCAL VOC 2012的数据集的下载链接的话，你可以试试：
https://pan.baidu.com/s/1CCR840MJ3Rx7jQ-r1jLX9g
提取码cl1e。
