### ISSUE TITLE
The aggregation of saliency map

### ISSUE THREAD

**Issue by mt-cly** [PengtaoJiang/L2G#7]
Hi, thanks for your work.
I have confusion in terms of the aggregation of the saliency map. After getting the local CAM, the saliency map is adopted to revise the pseudo mask as in https://github.com/PengtaoJiang/L2G/blob/main/scripts/train_l2g_sal_voc.py#L203 . It seems to remove a  CAM foreground region if the region has no overlap with the saliency map? i.e., the transfer loss would be `L_st =||0-G_i|| if |S_i|=0` instead of   `L_st =||A_i-G_i|| if |S_i|=0` as paper report. 
Thank you.

**Comment by PengtaoJiang** [comment]
Hello, @mt-cly. Later, we experiment on these two cases, i.e., ||0-G_i|| and ||A_i-G_i||. We obtain very close-quality pseudo labels.  We guess that the number of the case |S_i|=0 is very small. ||0-G_i|| occurs not frequently.  If you need the code, we can send it to you. I hope it will help.

**Comment by mt-cly** [comment]
Hi, thanks for your reply.
Okay, it seems does not a matter.
