### ISSUE TITLE
使用本代码进行训练过程中local loss变为nan

### ISSUE THREAD

**Issue by Lin-7** [PengtaoJiang/L2G#8]
您好，我使用本仓库提供的代码，安装了相关的依赖库（其中如torch，torchvision等框架包根据requirement.txt中的版本要求进行安装，其他依赖库由于版本兼容性原因，未指定版本安装）后，由于设备原因，将batchsize从3降至1在PASCAL VOC2012上训练分类模型（其他超参数没有进行修改），在训练过程中，local loss变为nan，请问您知道问题所在吗？
![image](https://user-images.githubusercontent.com/45335247/185568982-caef86ae-62a2-49d5-9b24-b9ac5b30b77b.png)
训练配置参数如下：
![image](https://user-images.githubusercontent.com/45335247/185569222-3821c235-e01c-4043-b217-e6c37e4bc23f.png)

**Comment by PengtaoJiang** [comment]
我们没有跑过这么小的batch size，可以考虑加个warm up 100 iterations.

**Comment by Lin-7** [comment]
问题已经通过调整iter_size解决，感谢您的回复~
